-- بيانات المهام الأولية (91 مهمة) المستوردة من ملف الإكسل
-- شغّلها بعد schema.sql. آمنة لإعادة التشغيل (تحذف ثم تُدرج).
truncate table public.tasks;
insert into public.tasks (order_index, activity, project, task, priority, status, assigned_to, due_date, waiting_on, blocker, approval_status, notes, health) values
(0, 'Administration', 'Seem prime', 'دراسة انشاء مركز القيادة والتحكم الموحد(GCC)', 'High', 'In Progress', 'Amal (AccounManager)', null, 'VULET', '', 'Pending Review', '', 'On Track'),
(1, 'Operation', 'Seem prime', 'العمل على انشاء بنية رقمية موحدة قابلة للتوسع ( Back-End)', 'High', 'In Progress', 'IT Team - ChatGate', null, 'SEEM', '', '', '', 'On Track'),
(2, 'Corporate Profile', 'Seem prime', 'Seem Prime Profile', 'High', 'Completed', 'Ahmad(Designer)', '2026-06-24', 'VULET', 'لم يتم الاعتماد وجاري التعديل', 'Reveision needed', '', 'Completed'),
(3, 'Website Development', 'Seem prime', 'Website company profile (WordPresss)', 'High', 'In Progress', 'Mubarak(IT)', '2026-07-21', 'VULET', 'بانتظار تسليم جميع الصلاحيات للوصول', '', '', 'At Risk'),
(4, 'Marketing', 'Seem prime', 'تفعيل حساب LinkenIn لسيم الاستثمارية', 'High', 'Completed', 'Amal (AccounManager)', '2026-06-22', 'VULET', '', '', '', 'Completed'),
(5, 'Marketing', 'Seem prime', 'اعداد خطة محتوى شهرية لحساب LinkedIn والمحتوى الشخصي للرئيس التنفيذي أ.سامي شبيلي', 'High', 'Not Started', 'Raed(Content Manger)', '2026-06-28', 'CONTENT', '', '', '', 'Delayed'),
(6, 'Operation', 'Homera', 'Scope of Work', 'High', 'Completed', 'Amal (AccounManager)', null, 'VULET', '', 'Pending Review', '', 'Completed'),
(7, 'Social Media Plan', 'Homera', 'انشاء الحسابات', 'High', 'Completed', 'Lujain(PM)', '2026-06-04', 'SEEM', '', '', '', 'Completed'),
(8, 'Advertising Plan', 'Homera', 'خطة الاعلانات ( Direct Sales)', 'High', 'Completed', 'Raed(Content Manager)', '2026-06-16', 'VULET', '', 'Pending Review', '', 'Completed'),
(9, 'Advertising Plan', 'Homera', 'المحتوى الإعلاني', 'High', 'In Progress', 'Raed(Content Manger)', '2026-07-14', 'VULET', '', '', '', 'Delayed'),
(10, 'Advertising Plan', 'Homera', 'تسليم المواد والمتطلبات المطلوبة', 'High', 'Completed', 'Mr.Sami (CEO)', '2026-06-23', 'SEEM', '', '', '', 'Completed'),
(11, 'Website Homera', 'Homera', 'العرض الفني لمنصة هوميرا الرقمية + التطبيق', 'High', 'On Hold', 'Mubrak (IT)', '2026-06-06', 'IT TEAM', '', 'Pending Review', '', 'Delayed'),
(12, 'Operation', 'Homera', 'اعتماد Supdomain خاص Homera.Homes , انشاء (Landing Page)', 'High', 'In Progress', 'Mubarak(IT)', '2026-07-02', 'IT TEAM', 'يتم الرفع على السيرفرات', 'Reveision needed', '', 'Delayed'),
(13, 'Marketing', 'Homera', 'اعداد المحتوى التعريفي للمنصات الرقمية لهوميرا (البيع المباشر)', 'High', 'Completed', 'Lujain(PM)', '2026-07-06', 'IT TEAM', '', 'Pending Review', '', 'Completed'),
(14, 'Marketing', 'Homera', 'إعداد وترتيب ملفات المشاريع بالمواصفات (كل مشروع على حدى)', 'High', 'In Progress', 'Lujain(PM)', '2026-07-06', 'VULET', '', '', '', 'Delayed'),
(15, 'Developments & Marketing', 'Homera', 'مراجعة سكوب شركة Chat Gate وعقد اجتماع لكيفية الاستفادة من خدماتها لهوميرا +عرض سعر', 'High', 'Completed', 'Amal (AccounManager)', '2026-07-06', 'SEEM', '', '', '', 'Completed'),
(16, 'Marketing Strategy', 'Homera', 'الخطة التسويقية', 'High', 'Completed', 'Lujain(PM)', '2026-07-09', 'VULET', '', '', '', 'Completed'),
(17, 'Advertising Plan', 'Homera', 'انشاء حساب فيسبوك شخصي', 'High', 'Not Started', 'MR.Sami (CEO)', '2026-07-12', 'SEEM', '', '', '', 'Delayed'),
(18, 'Developments & Marketing', 'Homera', 'Calender Events 2026-2027', 'High', 'Completed', 'Lujain(PM)', '2026-07-09', 'VULET', '', '', '', 'Completed'),
(19, 'Website Homera', 'Homera', 'ربط المنصة بـ ZL , eat plus', 'Low', 'On Hold', 'Mubrak (IT)', null, 'IT TEAM', '', '', '', 'On Track'),
(20, 'Landing Page', 'Homera', 'ملف تطوير صفحة هبوط هوميرا', 'High', 'Completed', 'Lujain(PM)', '2026-07-09', 'VULET', '', '', '', 'On Track'),
(21, 'Website Development', 'ZL.Tours', 'تطوير الواجهة للموقع', 'High', 'Completed', 'Ohood (IT )', '2026-06-13', 'IT TEAM', '', 'Reveision needed', '', 'Completed'),
(22, 'Website Development', 'ZL.Tours', 'تجربة المستخدم والواجهة الأمامية (Front-End)', 'High', 'Completed', 'Ohood (IT )', '2026-06-04', 'IT TEAM', '', 'Aprproved', '', 'Completed'),
(23, 'Website Development', 'ZL.Tours', 'تحسين تجربة تسجيل الدخول وطرق التسجيل برقم الجوال او الايميل', 'High', 'Completed', 'Ohood (IT )', '2026-06-04', 'IT TEAM', '', 'Aprproved', '', 'Completed'),
(24, 'Website Development', 'ZL.Tours', 'مراجعة وتحسين بعض عناصر التصميم والأزرار داخل الموقع', 'High', 'Completed', 'Ohood (IT )', '2026-06-04', 'IT TEAM', '', 'Pending Review', '', 'Completed'),
(25, 'Website Development', 'ZL.Tours', 'تجربة الحجز وانظمة الدفع وخيارات الدفع المتنوعة', 'High', 'Completed', 'Ohood (IT )', '2026-06-04', 'IT TEAM', '', 'Aprproved', '', 'Completed'),
(26, 'Website Development', 'ZL.Tours', 'ربط المنصة بـ Homera , eat plus', 'Low', 'On Hold', 'Ohood (IT )', null, 'IT TEAM', '', '', '', 'On Track'),
(27, 'Website Development', 'ZL.Tours', 'البيانات الموثقة والسجل التجاري داخل المنصة', 'High', 'Completed', 'Ohood (IT )', '2026-06-04', 'IT TEAM', '', 'Reveision needed', '', 'Completed'),
(28, 'Website Development', 'ZL.Tours', 'الاشعارات الخاصة بالعمليات والحجوزات عن طريق البريد الالكتروني', 'High', 'Completed', 'Ohood (IT )', '2026-06-04', 'IT TEAM', '', 'Reveision needed', '', 'Completed'),
(29, 'Website Development', 'ZL.Tours', 'اضافة ايقونات مرتبطة بالمدن لتسهيل تصفح الخدمات والوجهات السياحية', 'High', 'Completed', 'Ohood (IT )', null, 'IT TEAM', '', 'Pending Review', '', 'Completed'),
(30, 'Website Development', 'ZL.Tours', 'خدمة العملاء بـ AI مطور ومتعدد اللغات وتثبيته في الرئيسية', 'High', 'Completed', 'Ohood (IT )', '2026-06-04', 'IT TEAM', '', 'Reveision needed', '', 'Completed'),
(31, 'Website Development', 'ZL.Tours', 'ايقونة مزودي الخدمة بداخلها ادارة تواريخ اوقات الاتاحة (shop now)', 'High', 'Completed', 'Ohood (IT )', '2026-06-04', 'IT TEAM', '', '', '', 'Completed'),
(32, 'Website Development', 'ZL.Tours', 'اضافة خصومات وpromo code للسائح والمرشد', 'Medium', 'In Progress', 'Ohood (IT )', null, 'IT TEAM', '', '', '', 'On Track'),
(33, 'Workshops', 'ZL.Tours', 'التنسيق لورشة عمل خاصة بالمرشدين السياحيين لاستكمال البيانات+البطاقات', 'High', 'Completed', 'Vulet - Seem', '2026-06-13', 'SEEM', '', '', '', 'Completed'),
(34, 'Workshops', 'ZL.Tours', 'ورشة عمل لمزودي الخدمات والشركاء', 'Low', 'On Hold', 'Vulet - seem', null, 'SEEM', '', '', '', 'On Track'),
(35, 'Operation', 'ZL.Tours', 'Scope of Work', 'High', 'Completed', 'Amal (AccounManager)', '2026-06-21', 'VULET', '', 'Aprproved', '', 'Completed'),
(36, 'Website Development', 'ZL.Tours', 'تجهيز ملف التعديلات الخاصة بالواجهة الأمامية (Front-End)', 'High', 'Completed', 'Lujain(PM)', '2026-06-03', 'CONTENT', '', 'Aprproved', '', 'Completed'),
(37, 'Website Development', 'ZL.Tours', 'تجهيز ملف مراجعة الشعارات المعتمدة والمواد النهائية', 'High', 'Completed', 'Lujain(PM)', '2026-06-03', 'VULET', '', 'Aprproved', '', 'Completed'),
(38, 'Website Development', 'ZL.Tours', 'التطوير التقني وعلاج المشكلات والتحسينات', 'High', 'In Progress', 'Ohood (IT )Mubarak', null, 'VULET', '', 'Pending Review', '', 'On Track'),
(39, 'Website Development', 'ZL.Tours', 'الترجمة الكاملة للموقع', 'High', 'Completed', 'Ohood (IT )', '2026-06-11', 'VULET', '', '', '', 'Completed'),
(40, 'Website Development', 'ZL.Tours', 'تطوير الفلاتر الذكية', 'High', 'Completed', 'Ohood (IT )', '2026-06-04', 'IT TEAM', '', 'Aprproved', '', 'Completed'),
(41, 'Website Development', 'ZL.Tours', 'معالجة مشاكل الادمن', 'High', 'Completed', 'Ohood (IT )', '2026-06-04', 'VULET', '', '', '', 'Completed'),
(42, 'Website Development', 'ZL.Tours', 'مراجعة بوابة الدفع', 'High', 'Completed', 'Ohood (IT )', '2026-06-11', 'VULET', '', 'Pending Review', '', 'Completed'),
(43, 'Website Development', 'ZL.Tours', 'تحديث شعارات وسائل الدفع', 'High', 'Completed', 'Ohood (IT )', '2026-06-04', 'IT TEAM', '', 'Aprproved', 'بانتظار اضافة تابي', 'Completed'),
(44, 'Marketing Strategy', 'ZL.Tours', 'اعداد  الاستراتيجية والخطة التسويقية لمنصة زل', 'High', 'Completed', 'Lujain(PM)', '2026-07-01', 'VULET', '', '', '', 'Completed'),
(45, 'Advertising Plan', 'ZL.Tours', 'اعداد خطة الاعلانات', 'High', 'Completed', 'Raed(Content Manager)', '2026-06-28', 'VULET', '', '', '', 'Completed'),
(46, 'Website Development', 'ZL.Tours', 'خطة تطوير منصة زل (المرحلة الثانية )', 'High', 'Completed', 'Lujain(PM)', '2026-06-22', 'VULET', '', '', '', 'Completed'),
(47, 'Marketing', 'ZL.Tours', 'الاتفاق مع المصورين باعتماد المواد المرئية', 'High', 'In Progress', 'Lujain(PM)', '2026-07-08', 'VULET', '', '', '', 'Delayed'),
(48, '', 'ZL.Tours', 'الربط مع API الفعاليات للمنصة من وزارة السياحة.', 'High', 'In Progress', 'Lujain(PM)', null, 'VULET', 'لم يتم الرد', '', '', 'On Track'),
(49, 'Website Development', 'ZL.Tours', 'اضافة خانات في تجارب المرشد و توحيد الاسعار للمرشدين', 'High', 'Completed', 'Ohood(IT)', '2026-06-20', 'IT TEAM', 'لم تتم الاستجابة', '', '', 'Completed'),
(50, 'Website Development', 'ZL.Tours', 'اضافة موزدين خدمات', 'High', 'Completed', 'Ohood(IT)', '2026-06-20', 'IT TEAM', '', '', '', 'Completed'),
(51, 'Website Development', 'ZL.Tours', 'رقم غير مستخدم ل الرسائل المؤتمتة', 'High', 'Completed', 'Ohood(IT)', '2026-06-23', 'SEEM', '', '', '', 'Completed'),
(52, 'Website Development', 'ZL.Tours', 'خرائط التجربة', 'High', 'Completed', 'Ohood(IT)', '2026-06-23', 'IT TEAM', '', '', '', 'Completed'),
(53, 'Website Development', 'ZL.Tours', 'نمذجة بطاقات المرشدين وتجويد الباقة', 'High', 'Completed', 'Lujain(PM)', '2026-06-23', 'CONTENT', '', '', '', 'Completed'),
(54, 'Website Development', 'ZL.Tours', 'ملف تطويري للمنصة بالكامل (تسويق وتصميم ومحتوى)', 'High', 'In Progress', 'Lujain(PM)', '2026-07-07', 'VULET', '', '', '', 'Delayed'),
(55, 'Advertising Plan', 'ZL.Tours', 'اطلاق الحملات الإعلانية سناب شات بميزانية مبدئية 1000 دولار .', 'High', 'Completed', 'Asem(MediaPayer)', '2026-07-06', 'VULET', '', '', '', 'Completed'),
(56, 'Advertising Plan', 'ZL.Tours', 'اطلاق الحملات الاعلانية انستغرام و تيك توك وبقية المنصات الرقمية.', 'High', 'Not Started', 'Asem(MediaPayer)', null, 'VULET', '', '', '', 'On Track'),
(57, 'Advertising Plan', 'ZL.Tours', 'تقريرأداء  الحملة الاعلانية وسلوك المستخدمين في منصة زل.', 'High', 'Completed', 'Asem(MediaPayer)', '2026-07-12', 'VULET', '', 'Pending Review', '', 'Completed'),
(58, 'Analysis & Comparison', 'ZL.Tours', 'ملف دراسة مقارنة بين GetYourGuide و زِل', 'High', 'Completed', 'Lujain(PM)', '2026-07-13', '', '', '', '', 'On Track'),
(59, 'Website Development', 'ZL.Tours', 'نطاق التسعير الجديد في المنصة', 'High', 'In Progress', 'Ohood (IT)', '2026-07-19', '', '', '', '', 'On Track'),
(60, 'Website Development', 'ZL.Tours', 'الدعم الفني للمنصة', 'High', 'In Progress', 'Ohood(IT)', '2026-07-17', '', '', '', '', 'On Track'),
(61, 'Advertising Plan', 'ZL.Tours', 'تصاميم ومحتوى زل الدفعة الثانية', 'High', 'In Progress', 'Raed(Conent Manager)', null, '', '', '', '', 'On Track'),
(62, 'Advertising Plan', 'ZL.Tours', 'تصوير بودكاست مع أ.حسن فقيه لليوم الوطني', 'High', 'Not Started', 'Vulet Team', '2026-08-02', 'VULET', '', '', '', 'On Track'),
(63, 'Branding & Packaging', 'Jaz chocolate', 'المتطلبات العامة للاعمال الفنية (اسم اللوحة - القصة - التوقيع) وبطاقة المعلومات', 'High', 'Completed', 'Wajd (PM)', '2026-06-15', 'VULET', 'جاري التعديل على المحتوى مع كاتبة المحتوى فاطمة', '', '', 'Completed'),
(64, 'Art Direction', 'Jaz chocolate', 'الدفعات والتسعير وعقود الفنانين', 'High', 'Completed', 'Wajd (PM)', '2026-06-10', 'SEEM', '', 'Aprproved', 'توحيد سعر جميع الاعمال 2000 ريال', 'Completed'),
(65, 'Artwork', 'Jaz chocolate', 'تجهيز الأعمال الفنية', 'High', 'Completed', 'Wajd (PM)', '2026-06-23', 'VULET', 'جاري اضافة تعديلات مم ادى الى تاخير العمل', 'Pending Review', '', 'Completed'),
(66, 'Packaging', 'Jaz chocolate', 'تصميم عبوة الهدايا 200 جرام', 'High', 'Completed', 'Enas(Designer)', '2026-06-15', 'VULET', 'تم الرفض من قبل مديرة المشروع للتعديل', 'Pending Review', '', 'Completed'),
(67, 'Packaging', 'Jaz chocolate', 'تغليف الـ Dessert', 'High', 'On Hold', 'Enas (Designer)', '2026-06-15', 'VULET', 'لازالت تحت التعديل', 'Reveision needed', '', 'Delayed'),
(68, 'Operation', 'Jaz chocolate', 'تصميم اللوحات الإرشادية داخل مصنع JAZ', 'Low', 'Not Started', 'Ahmad (Designer)', '2026-06-30', 'SEEM', 'تزويد الفريق بالبيانات', '', '', 'Delayed'),
(69, 'Profile & Branding', 'Jaz chocolate', 'العرض الحكومي (Presentation)', 'High', 'Completed', 'Ahmad (Designer)', '2026-06-01', 'VULET', '', 'Pending Review', '', 'Completed'),
(70, 'Packaging', 'Jaz chocolate', 'تجهيز واستلام القيم الغذائية للمنتج', 'High', 'Completed', 'Wajd (PM)', null, 'SEEM', 'بانتظار الدكتورة منال', '', '', 'Completed'),
(71, 'Social Media Plan', 'Jaz chocolate', 'انشاء الحسابات', 'High', 'Completed', 'Wajd (PM)', '2026-06-08', 'VULET', '', 'Aprproved', 'تحتاج تعديلات', 'Completed'),
(72, 'Branding & Packaging', 'Jaz chocolate', 'اعداد ملف باسم كل مجموعة', 'High', 'On Hold', 'Wajd (PM)', null, 'VULET', '', 'Pending Review', '', 'On Track'),
(73, 'Website', 'Jaz chocolate', 'منصة جاز الالكترونية', 'High', 'In Progress', 'Mubarak(IT)', '2026-08-01', 'VULET', '', '', '', 'On Track'),
(74, 'Marketing', 'Jaz chocolate', 'اعداد الاستراتيجية و الخطة التسويقية', 'High', 'Completed', 'Wajd (PM)', '2026-07-04', 'VULET', '', '', '', 'Completed'),
(75, 'Branding', 'Jaz chocolate', 'قصة جاز', 'High', 'Completed', 'Fatimah(Content)', '2026-06-13', 'SEEM', '', 'Pending Review', '', 'Completed'),
(76, 'Marketing', 'Jaz chocolate', 'كتابة سيناريوالفيلم السينمائي', 'High', 'Completed', 'Fatimah(Content )', '2026-06-21', 'CONTENT', '', '', '', 'Completed'),
(77, 'Marketing', 'Jaz chocolate', 'انتاج وتصوير الفيلم', 'High', 'Not Started', 'Photography Team', '2026-07-20', 'VULET', '', '', '', 'At Risk'),
(78, 'Profile & Branding', 'Jaz chocolate', 'الهوية البصرية لـ حاني', 'Low', 'On Hold', 'Ahmad (Designer)', null, 'SEEM', '', '', '', 'On Track'),
(79, 'Profile & Branding', 'Jaz chocolate', 'الهوية البصرية لـ شهدان', 'Low', 'On Hold', 'AHmad (Designer)', null, 'SEEM', '', '', '', 'On Track'),
(80, 'Profile & Branding', 'Jaz chocolate', 'الهوية البصرية لـ حوايج', 'Low', 'On Hold', 'AHmad (Designer)', null, 'SEEM', '', '', '', 'On Track'),
(81, 'Branding', 'Jaz chocolate', 'تسليم واستلام الأعمال الفنية لمقر الشركة', 'High', 'Completed', 'Wajd (PM)', '2026-07-02', 'VULET', '', '', '', 'Completed'),
(82, 'Branding', 'Jaz chocolate', '( Cart - Pull out box 30g - Pull out box 100g- box 250g -economical box )تسليم جميع تصاميم جاز', 'High', 'In Progress', 'Wajd (PM)', '2026-07-11', 'VULET', 'تحت التعديل', 'Rejected', '', 'Delayed'),
(83, 'Advertising Plan', 'Jaz chocolate', 'انشاء الحسابات الإعلانية لجاز', 'High', 'Not Started', 'Asem(MediaPayer)', '2026-07-15', 'VULET', '', '', '', 'On Track'),
(84, 'Branding', 'Jaz chocolate', 'تسليم أعمال جاز للمطبعة', 'High', 'Completed', 'wajd (PM)', '2026-07-15', 'VULET', 'تم تسليم مطبوعات ١٠٠ ج و ٣٠ ج متبقي تصاميم بوكس الاهداء ٢٥٠ ج و٥٠٠ ج و ٥ج', '', '', 'On Track'),
(85, '', 'Jaz chocolate', 'اجتماع مع الإدارة المالية بخصوص منصة جاز', 'High', 'In Progress', 'Mubarak(IT)', '2026-07-18', '', '', '', '', 'On Track'),
(86, 'Marketing', 'eat plus', 'استلام الاستراتيجية والخطة التسويقية من الشركة المطورة للمنصة', 'High', 'Completed', 'Vulet Team', '2026-07-06', 'VULET', '', '', '', 'Completed'),
(87, 'Marketing', 'eat plus', 'تفعيل الاستراتيجية التسويقية من الشركة المطورة للمنصة ومراجعتها', 'High', 'Completed', 'Wajd (PM)', '2026-07-09', 'VULET', '', '', '', 'Completed'),
(88, 'Advertising Plan', 'eat plus', 'اعداد ملف الفئات المستهدفة لمزودين خدمات التطبيق', 'Medium', 'On Hold', 'Raed(Content Manager)', null, 'VULET', '', '', '', 'On Track'),
(89, 'Operation', 'eat plus', '', 'High', 'In Progress', 'Wajd (PM)', '2026-07-13', 'VULET', '', '', '', 'On Track'),
(90, 'Marketing', 'eat plus', 'تطويروتطبيق الاستراتجية  والخطة التسويقية', 'Medium', 'In Progress', 'Wajd (PM)', '2026-07-16', 'VULET', '', '', '', 'On Track');
