// بيانات المهام الأولية المستوردة من ملف الإكسل (Seem Prime)
// تُستخدم لتعبئة قاعدة البيانات (seed) وللوضع المحلي.
export const SEED_TASKS = [
  {
    "activity": "Administration",
    "project": "Seem prime",
    "task": "دراسة انشاء مركز القيادة والتحكم الموحد(GCC)",
    "priority": "High",
    "status": "In Progress",
    "assigned_to": "Amal (AccounManager)",
    "due_date": "",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "Pending Review",
    "notes": "",
    "health": "On Track"
  },
  {
    "activity": "Operation",
    "project": "Seem prime",
    "task": "العمل على انشاء بنية رقمية موحدة قابلة للتوسع ( Back-End)",
    "priority": "High",
    "status": "In Progress",
    "assigned_to": "IT Team - ChatGate",
    "due_date": "",
    "waiting_on": "SEEM",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "On Track"
  },
  {
    "activity": "Corporate Profile",
    "project": "Seem prime",
    "task": "Seem Prime Profile",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Ahmad(Designer)",
    "due_date": "2026-06-24",
    "waiting_on": "VULET",
    "blocker": "لم يتم الاعتماد وجاري التعديل",
    "approval_status": "Reveision needed",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "Seem prime",
    "task": "Website company profile (WordPresss)",
    "priority": "High",
    "status": "In Progress",
    "assigned_to": "Mubarak(IT)",
    "due_date": "2026-07-21",
    "waiting_on": "VULET",
    "blocker": "بانتظار تسليم جميع الصلاحيات للوصول",
    "approval_status": "",
    "notes": "",
    "health": "At Risk"
  },
  {
    "activity": "Marketing",
    "project": "Seem prime",
    "task": "تفعيل حساب LinkenIn لسيم الاستثمارية",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Amal (AccounManager)",
    "due_date": "2026-06-22",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Marketing",
    "project": "Seem prime",
    "task": "اعداد خطة محتوى شهرية لحساب LinkedIn والمحتوى الشخصي للرئيس التنفيذي أ.سامي شبيلي",
    "priority": "High",
    "status": "Not Started",
    "assigned_to": "Raed(Content Manger)",
    "due_date": "2026-06-28",
    "waiting_on": "CONTENT",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Delayed"
  },
  {
    "activity": "Operation",
    "project": "Homera",
    "task": "Scope of Work",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Amal (AccounManager)",
    "due_date": "",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "Pending Review",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Social Media Plan",
    "project": "Homera",
    "task": "انشاء الحسابات",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Lujain(PM)",
    "due_date": "2026-06-04",
    "waiting_on": "SEEM",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Advertising Plan",
    "project": "Homera",
    "task": "خطة الاعلانات ( Direct Sales)",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Raed(Content Manager)",
    "due_date": "2026-06-16",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "Pending Review",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Advertising Plan",
    "project": "Homera",
    "task": "المحتوى الإعلاني",
    "priority": "High",
    "status": "In Progress",
    "assigned_to": "Raed(Content Manger)",
    "due_date": "2026-07-14",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Delayed"
  },
  {
    "activity": "Advertising Plan",
    "project": "Homera",
    "task": "تسليم المواد والمتطلبات المطلوبة",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Mr.Sami (CEO)",
    "due_date": "2026-06-23",
    "waiting_on": "SEEM",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Homera",
    "project": "Homera",
    "task": "العرض الفني لمنصة هوميرا الرقمية + التطبيق",
    "priority": "High",
    "status": "On Hold",
    "assigned_to": "Mubrak (IT)",
    "due_date": "2026-06-06",
    "waiting_on": "IT TEAM",
    "blocker": "",
    "approval_status": "Pending Review",
    "notes": "",
    "health": "Delayed"
  },
  {
    "activity": "Operation",
    "project": "Homera",
    "task": "اعتماد Supdomain خاص Homera.Homes , انشاء (Landing Page)",
    "priority": "High",
    "status": "In Progress",
    "assigned_to": "Mubarak(IT)",
    "due_date": "2026-07-02",
    "waiting_on": "IT TEAM",
    "blocker": "يتم الرفع على السيرفرات",
    "approval_status": "Reveision needed",
    "notes": "",
    "health": "Delayed"
  },
  {
    "activity": "Marketing",
    "project": "Homera",
    "task": "اعداد المحتوى التعريفي للمنصات الرقمية لهوميرا (البيع المباشر)",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Lujain(PM)",
    "due_date": "2026-07-06",
    "waiting_on": "IT TEAM",
    "blocker": "",
    "approval_status": "Pending Review",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Marketing",
    "project": "Homera",
    "task": "إعداد وترتيب ملفات المشاريع بالمواصفات (كل مشروع على حدى)",
    "priority": "High",
    "status": "In Progress",
    "assigned_to": "Lujain(PM)",
    "due_date": "2026-07-06",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Delayed"
  },
  {
    "activity": "Developments & Marketing",
    "project": "Homera",
    "task": "مراجعة سكوب شركة Chat Gate وعقد اجتماع لكيفية الاستفادة من خدماتها لهوميرا +عرض سعر",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Amal (AccounManager)",
    "due_date": "2026-07-06",
    "waiting_on": "SEEM",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Marketing Strategy",
    "project": "Homera",
    "task": "الخطة التسويقية",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Lujain(PM)",
    "due_date": "2026-07-09",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Advertising Plan",
    "project": "Homera",
    "task": "انشاء حساب فيسبوك شخصي",
    "priority": "High",
    "status": "Not Started",
    "assigned_to": "MR.Sami (CEO)",
    "due_date": "2026-07-12",
    "waiting_on": "SEEM",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Delayed"
  },
  {
    "activity": "Developments & Marketing",
    "project": "Homera",
    "task": "Calender Events 2026-2027",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Lujain(PM)",
    "due_date": "2026-07-09",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Homera",
    "project": "Homera",
    "task": "ربط المنصة بـ ZL , eat plus",
    "priority": "Low",
    "status": "On Hold",
    "assigned_to": "Mubrak (IT)",
    "due_date": "",
    "waiting_on": "IT TEAM",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "On Track"
  },
  {
    "activity": "Landing Page",
    "project": "Homera",
    "task": "ملف تطوير صفحة هبوط هوميرا",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Lujain(PM)",
    "due_date": "2026-07-09",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": ""
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "تطوير الواجهة للموقع",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Ohood (IT )",
    "due_date": "2026-06-13",
    "waiting_on": "IT TEAM",
    "blocker": "",
    "approval_status": "Reveision needed",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "تجربة المستخدم والواجهة الأمامية (Front-End)",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Ohood (IT )",
    "due_date": "2026-06-04",
    "waiting_on": "IT TEAM",
    "blocker": "",
    "approval_status": "Aprproved",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "تحسين تجربة تسجيل الدخول وطرق التسجيل برقم الجوال او الايميل",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Ohood (IT )",
    "due_date": "2026-06-04",
    "waiting_on": "IT TEAM",
    "blocker": "",
    "approval_status": "Aprproved",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "مراجعة وتحسين بعض عناصر التصميم والأزرار داخل الموقع",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Ohood (IT )",
    "due_date": "2026-06-04",
    "waiting_on": "IT TEAM",
    "blocker": "",
    "approval_status": "Pending Review",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "تجربة الحجز وانظمة الدفع وخيارات الدفع المتنوعة",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Ohood (IT )",
    "due_date": "2026-06-04",
    "waiting_on": "IT TEAM",
    "blocker": "",
    "approval_status": "Aprproved",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "ربط المنصة بـ Homera , eat plus",
    "priority": "Low",
    "status": "On Hold",
    "assigned_to": "Ohood (IT )",
    "due_date": "",
    "waiting_on": "IT TEAM",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "On Track"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "البيانات الموثقة والسجل التجاري داخل المنصة",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Ohood (IT )",
    "due_date": "2026-06-04",
    "waiting_on": "IT TEAM",
    "blocker": "",
    "approval_status": "Reveision needed",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "الاشعارات الخاصة بالعمليات والحجوزات عن طريق البريد الالكتروني",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Ohood (IT )",
    "due_date": "2026-06-04",
    "waiting_on": "IT TEAM",
    "blocker": "",
    "approval_status": "Reveision needed",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "اضافة ايقونات مرتبطة بالمدن لتسهيل تصفح الخدمات والوجهات السياحية",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Ohood (IT )",
    "due_date": "",
    "waiting_on": "IT TEAM",
    "blocker": "",
    "approval_status": "Pending Review",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "خدمة العملاء بـ AI مطور ومتعدد اللغات وتثبيته في الرئيسية",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Ohood (IT )",
    "due_date": "2026-06-04",
    "waiting_on": "IT TEAM",
    "blocker": "",
    "approval_status": "Reveision needed",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "ايقونة مزودي الخدمة بداخلها ادارة تواريخ اوقات الاتاحة (shop now)",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Ohood (IT )",
    "due_date": "2026-06-04",
    "waiting_on": "IT TEAM",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "اضافة خصومات وpromo code للسائح والمرشد",
    "priority": "Medium",
    "status": "In Progress",
    "assigned_to": "Ohood (IT )",
    "due_date": "",
    "waiting_on": "IT TEAM",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "On Track"
  },
  {
    "activity": "Workshops",
    "project": "ZL.Tours",
    "task": "التنسيق لورشة عمل خاصة بالمرشدين السياحيين لاستكمال البيانات+البطاقات",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Vulet - Seem",
    "due_date": "2026-06-13",
    "waiting_on": "SEEM",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Workshops",
    "project": "ZL.Tours",
    "task": "ورشة عمل لمزودي الخدمات والشركاء",
    "priority": "Low",
    "status": "On Hold",
    "assigned_to": "Vulet - seem",
    "due_date": "",
    "waiting_on": "SEEM",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "On Track"
  },
  {
    "activity": "Operation",
    "project": "ZL.Tours",
    "task": "Scope of Work",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Amal (AccounManager)",
    "due_date": "2026-06-21",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "Aprproved",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "تجهيز ملف التعديلات الخاصة بالواجهة الأمامية (Front-End)",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Lujain(PM)",
    "due_date": "2026-06-03",
    "waiting_on": "CONTENT",
    "blocker": "",
    "approval_status": "Aprproved",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "تجهيز ملف مراجعة الشعارات المعتمدة والمواد النهائية",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Lujain(PM)",
    "due_date": "2026-06-03",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "Aprproved",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "التطوير التقني وعلاج المشكلات والتحسينات",
    "priority": "High",
    "status": "In Progress",
    "assigned_to": "Ohood (IT )Mubarak",
    "due_date": "",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "Pending Review",
    "notes": "",
    "health": "On Track"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "الترجمة الكاملة للموقع",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Ohood (IT )",
    "due_date": "2026-06-11",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "تطوير الفلاتر الذكية",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Ohood (IT )",
    "due_date": "2026-06-04",
    "waiting_on": "IT TEAM",
    "blocker": "",
    "approval_status": "Aprproved",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "معالجة مشاكل الادمن",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Ohood (IT )",
    "due_date": "2026-06-04",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "مراجعة بوابة الدفع",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Ohood (IT )",
    "due_date": "2026-06-11",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "Pending Review",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "تحديث شعارات وسائل الدفع",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Ohood (IT )",
    "due_date": "2026-06-04",
    "waiting_on": "IT TEAM",
    "blocker": "",
    "approval_status": "Aprproved",
    "notes": "بانتظار اضافة تابي",
    "health": "Completed"
  },
  {
    "activity": "Marketing Strategy",
    "project": "ZL.Tours",
    "task": "اعداد  الاستراتيجية والخطة التسويقية لمنصة زل",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Lujain(PM)",
    "due_date": "2026-07-01",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Advertising Plan",
    "project": "ZL.Tours",
    "task": "اعداد خطة الاعلانات",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Raed(Content Manager)",
    "due_date": "2026-06-28",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "خطة تطوير منصة زل (المرحلة الثانية )",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Lujain(PM)",
    "due_date": "2026-06-22",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Marketing",
    "project": "ZL.Tours",
    "task": "الاتفاق مع المصورين باعتماد المواد المرئية",
    "priority": "High",
    "status": "In Progress",
    "assigned_to": "Lujain(PM)",
    "due_date": "2026-07-08",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Delayed"
  },
  {
    "activity": "",
    "project": "ZL.Tours",
    "task": "الربط مع API الفعاليات للمنصة من وزارة السياحة.",
    "priority": "High",
    "status": "In Progress",
    "assigned_to": "Lujain(PM)",
    "due_date": "",
    "waiting_on": "VULET",
    "blocker": "لم يتم الرد",
    "approval_status": "",
    "notes": "",
    "health": "On Track"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "اضافة خانات في تجارب المرشد و توحيد الاسعار للمرشدين",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Ohood(IT)",
    "due_date": "2026-06-20",
    "waiting_on": "IT TEAM",
    "blocker": "لم تتم الاستجابة",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "اضافة موزدين خدمات",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Ohood(IT)",
    "due_date": "2026-06-20",
    "waiting_on": "IT TEAM",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "رقم غير مستخدم ل الرسائل المؤتمتة",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Ohood(IT)",
    "due_date": "2026-06-23",
    "waiting_on": "SEEM",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "خرائط التجربة",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Ohood(IT)",
    "due_date": "2026-06-23",
    "waiting_on": "IT TEAM",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "نمذجة بطاقات المرشدين وتجويد الباقة",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Lujain(PM)",
    "due_date": "2026-06-23",
    "waiting_on": "CONTENT",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "ملف تطويري للمنصة بالكامل (تسويق وتصميم ومحتوى)",
    "priority": "High",
    "status": "In Progress",
    "assigned_to": "Lujain(PM)",
    "due_date": "2026-07-07",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Delayed"
  },
  {
    "activity": "Advertising Plan",
    "project": "ZL.Tours",
    "task": "اطلاق الحملات الإعلانية سناب شات بميزانية مبدئية 1000 دولار .",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Asem(MediaPayer)",
    "due_date": "2026-07-06",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Advertising Plan",
    "project": "ZL.Tours",
    "task": "اطلاق الحملات الاعلانية انستغرام و تيك توك وبقية المنصات الرقمية.",
    "priority": "High",
    "status": "Not Started",
    "assigned_to": "Asem(MediaPayer)",
    "due_date": "",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "On Track"
  },
  {
    "activity": "Advertising Plan",
    "project": "ZL.Tours",
    "task": "تقريرأداء  الحملة الاعلانية وسلوك المستخدمين في منصة زل.",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Asem(MediaPayer)",
    "due_date": "2026-07-12",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "Pending Review",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Analysis & Comparison",
    "project": "ZL.Tours",
    "task": "ملف دراسة مقارنة بين GetYourGuide و زِل",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Lujain(PM)",
    "due_date": "2026-07-13",
    "waiting_on": "",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": ""
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "نطاق التسعير الجديد في المنصة",
    "priority": "High",
    "status": "In Progress",
    "assigned_to": "Ohood (IT)",
    "due_date": "2026-07-19",
    "waiting_on": "",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": ""
  },
  {
    "activity": "Website Development",
    "project": "ZL.Tours",
    "task": "الدعم الفني للمنصة",
    "priority": "High",
    "status": "In Progress",
    "assigned_to": "Ohood(IT)",
    "due_date": "2026-07-17",
    "waiting_on": "",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": ""
  },
  {
    "activity": "Advertising Plan",
    "project": "ZL.Tours",
    "task": "تصاميم ومحتوى زل الدفعة الثانية",
    "priority": "High",
    "status": "In Progress",
    "assigned_to": "Raed(Conent Manager)",
    "due_date": "",
    "waiting_on": "",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": ""
  },
  {
    "activity": "Advertising Plan",
    "project": "ZL.Tours",
    "task": "تصوير بودكاست مع أ.حسن فقيه لليوم الوطني",
    "priority": "High",
    "status": "Not Started",
    "assigned_to": "Vulet Team",
    "due_date": "2026-08-02",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": ""
  },
  {
    "activity": "Branding & Packaging",
    "project": "Jaz chocolate",
    "task": "المتطلبات العامة للاعمال الفنية (اسم اللوحة - القصة - التوقيع) وبطاقة المعلومات",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Wajd (PM)",
    "due_date": "2026-06-15",
    "waiting_on": "VULET",
    "blocker": "جاري التعديل على المحتوى مع كاتبة المحتوى فاطمة",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Art Direction",
    "project": "Jaz chocolate",
    "task": "الدفعات والتسعير وعقود الفنانين",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Wajd (PM)",
    "due_date": "2026-06-10",
    "waiting_on": "SEEM",
    "blocker": "",
    "approval_status": "Aprproved",
    "notes": "توحيد سعر جميع الاعمال 2000 ريال",
    "health": "Completed"
  },
  {
    "activity": "Artwork",
    "project": "Jaz chocolate",
    "task": "تجهيز الأعمال الفنية",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Wajd (PM)",
    "due_date": "2026-06-23",
    "waiting_on": "VULET",
    "blocker": "جاري اضافة تعديلات مم ادى الى تاخير العمل",
    "approval_status": "Pending Review",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Packaging",
    "project": "Jaz chocolate",
    "task": "تصميم عبوة الهدايا 200 جرام",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Enas(Designer)",
    "due_date": "2026-06-15",
    "waiting_on": "VULET",
    "blocker": "تم الرفض من قبل مديرة المشروع للتعديل",
    "approval_status": "Pending Review",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Packaging",
    "project": "Jaz chocolate",
    "task": "تغليف الـ Dessert",
    "priority": "High",
    "status": "On Hold",
    "assigned_to": "Enas (Designer)",
    "due_date": "2026-06-15",
    "waiting_on": "VULET",
    "blocker": "لازالت تحت التعديل",
    "approval_status": "Reveision needed",
    "notes": "",
    "health": "Delayed"
  },
  {
    "activity": "Operation",
    "project": "Jaz chocolate",
    "task": "تصميم اللوحات الإرشادية داخل مصنع JAZ",
    "priority": "Low",
    "status": "Not Started",
    "assigned_to": "Ahmad (Designer)",
    "due_date": "2026-06-30",
    "waiting_on": "SEEM",
    "blocker": "تزويد الفريق بالبيانات",
    "approval_status": "",
    "notes": "",
    "health": "Delayed"
  },
  {
    "activity": "Profile & Branding",
    "project": "Jaz chocolate",
    "task": "العرض الحكومي (Presentation)",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Ahmad (Designer)",
    "due_date": "2026-06-01",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "Pending Review",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Packaging",
    "project": "Jaz chocolate",
    "task": "تجهيز واستلام القيم الغذائية للمنتج",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Wajd (PM)",
    "due_date": "",
    "waiting_on": "SEEM",
    "blocker": "بانتظار الدكتورة منال",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Social Media Plan",
    "project": "Jaz chocolate",
    "task": "انشاء الحسابات",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Wajd (PM)",
    "due_date": "2026-06-08",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "Aprproved",
    "notes": "تحتاج تعديلات",
    "health": "Completed"
  },
  {
    "activity": "Branding & Packaging",
    "project": "Jaz chocolate",
    "task": "اعداد ملف باسم كل مجموعة",
    "priority": "High",
    "status": "On Hold",
    "assigned_to": "Wajd (PM)",
    "due_date": "",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "Pending Review",
    "notes": "",
    "health": "On Track"
  },
  {
    "activity": "Website",
    "project": "Jaz chocolate",
    "task": "منصة جاز الالكترونية",
    "priority": "High",
    "status": "In Progress",
    "assigned_to": "Mubarak(IT)",
    "due_date": "2026-08-01",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "On Track"
  },
  {
    "activity": "Marketing",
    "project": "Jaz chocolate",
    "task": "اعداد الاستراتيجية و الخطة التسويقية",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Wajd (PM)",
    "due_date": "2026-07-04",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Branding",
    "project": "Jaz chocolate",
    "task": "قصة جاز",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Fatimah(Content)",
    "due_date": "2026-06-13",
    "waiting_on": "SEEM",
    "blocker": "",
    "approval_status": "Pending Review",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Marketing",
    "project": "Jaz chocolate",
    "task": "كتابة سيناريوالفيلم السينمائي",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Fatimah(Content )",
    "due_date": "2026-06-21",
    "waiting_on": "CONTENT",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Marketing",
    "project": "Jaz chocolate",
    "task": "انتاج وتصوير الفيلم",
    "priority": "High",
    "status": "Not Started",
    "assigned_to": "Photography Team",
    "due_date": "2026-07-20",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "At Risk"
  },
  {
    "activity": "Profile & Branding",
    "project": "Jaz chocolate",
    "task": "الهوية البصرية لـ حاني",
    "priority": "Low",
    "status": "On Hold",
    "assigned_to": "Ahmad (Designer)",
    "due_date": "",
    "waiting_on": "SEEM",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "On Track"
  },
  {
    "activity": "Profile & Branding",
    "project": "Jaz chocolate",
    "task": "الهوية البصرية لـ شهدان",
    "priority": "Low",
    "status": "On Hold",
    "assigned_to": "AHmad (Designer)",
    "due_date": "",
    "waiting_on": "SEEM",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "On Track"
  },
  {
    "activity": "Profile & Branding",
    "project": "Jaz chocolate",
    "task": "الهوية البصرية لـ حوايج",
    "priority": "Low",
    "status": "On Hold",
    "assigned_to": "AHmad (Designer)",
    "due_date": "",
    "waiting_on": "SEEM",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "On Track"
  },
  {
    "activity": "Branding",
    "project": "Jaz chocolate",
    "task": "تسليم واستلام الأعمال الفنية لمقر الشركة",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Wajd (PM)",
    "due_date": "2026-07-02",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Branding",
    "project": "Jaz chocolate",
    "task": "( Cart - Pull out box 30g - Pull out box 100g- box 250g -economical box )تسليم جميع تصاميم جاز",
    "priority": "High",
    "status": "In Progress",
    "assigned_to": "Wajd (PM)",
    "due_date": "2026-07-11",
    "waiting_on": "VULET",
    "blocker": "تحت التعديل",
    "approval_status": "Rejected",
    "notes": "",
    "health": "Delayed"
  },
  {
    "activity": "Advertising Plan",
    "project": "Jaz chocolate",
    "task": "انشاء الحسابات الإعلانية لجاز",
    "priority": "High",
    "status": "Not Started",
    "assigned_to": "Asem(MediaPayer)",
    "due_date": "2026-07-15",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": ""
  },
  {
    "activity": "Branding",
    "project": "Jaz chocolate",
    "task": "تسليم أعمال جاز للمطبعة",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "wajd (PM)",
    "due_date": "2026-07-15",
    "waiting_on": "VULET",
    "blocker": "تم تسليم مطبوعات ١٠٠ ج و ٣٠ ج متبقي تصاميم بوكس الاهداء ٢٥٠ ج و٥٠٠ ج و ٥ج",
    "approval_status": "",
    "notes": "",
    "health": ""
  },
  {
    "activity": "",
    "project": "Jaz chocolate",
    "task": "اجتماع مع الإدارة المالية بخصوص منصة جاز",
    "priority": "High",
    "status": "In Progress",
    "assigned_to": "Mubarak(IT)",
    "due_date": "2026-07-18",
    "waiting_on": "",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": ""
  },
  {
    "activity": "Marketing",
    "project": "eat plus",
    "task": "استلام الاستراتيجية والخطة التسويقية من الشركة المطورة للمنصة",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Vulet Team",
    "due_date": "2026-07-06",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Marketing",
    "project": "eat plus",
    "task": "تفعيل الاستراتيجية التسويقية من الشركة المطورة للمنصة ومراجعتها",
    "priority": "High",
    "status": "Completed",
    "assigned_to": "Wajd (PM)",
    "due_date": "2026-07-09",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "Completed"
  },
  {
    "activity": "Advertising Plan",
    "project": "eat plus",
    "task": "اعداد ملف الفئات المستهدفة لمزودين خدمات التطبيق",
    "priority": "Medium",
    "status": "On Hold",
    "assigned_to": "Raed(Content Manager)",
    "due_date": "",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": "On Track"
  },
  {
    "activity": "Operation",
    "project": "eat plus",
    "task": "",
    "priority": "High",
    "status": "In Progress",
    "assigned_to": "Wajd (PM)",
    "due_date": "2026-07-13",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": ""
  },
  {
    "activity": "Marketing",
    "project": "eat plus",
    "task": "تطويروتطبيق الاستراتجية  والخطة التسويقية",
    "priority": "Medium",
    "status": "In Progress",
    "assigned_to": "Wajd (PM)",
    "due_date": "2026-07-16",
    "waiting_on": "VULET",
    "blocker": "",
    "approval_status": "",
    "notes": "",
    "health": ""
  }
];
